### ISSUE TITLE
0.1.18 not working with `sbt-scalafix` 0.9.28

### ISSUE THREAD

**Issue by therockstorm** [vovapolu/scaluzzi#18]
The latest `sbt-scalafix` is using `scalameta` 4.4.18 and is updated to work with Scala 2.13.6. When I try to run either the `MissingFinal` or `Disable` rules using `scaluzzi` 0.1.18 with the other versions mentioned, I get the following error,

```
[error] scalafix.internal.v1.FileException: unexpected error processing file /Users/xxx/yyy.scala
[error] Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 60
[error] 	at scala.tools.asm.ClassReader.<init>(ClassReader.java:196)
[error] 	at scala.tools.asm.ClassReader.<init>(ClassReader.java:177)
[error] 	at scala.tools.asm.ClassReader.<init>(ClassReader.java:163)
[error] 	at scala.tools.asm.ClassReader.<init>(ClassReader.java:284)
[error] 	at scala.meta.internal.metacp.package$.scala$meta$internal$metacp$package$$readInputStreamToClassNode(package.scala:89)
[error] 	at scala.meta.internal.metacp.package$XtensionAsmClassfileOps.hasScalaSig(package.scala:78)
[error] 	at scala.meta.internal.scalacp.SymbolIndex.$anonfun$lookup$1(SymbolIndex.scala:30)
[error] 	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
[error] 	at scala.meta.internal.scalacp.SymbolIndex.lookup(SymbolIndex.scala:13
[error] 	at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSpec.descriptor(SymbolOps.scala:113)
[error] 	at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.uncached$1(SymbolOps.scala:18)
[error] 	at scala.meta.internal.scalacp.SymbolOps$XtensionSymbolSSymbol.toSemantic(SymbolOps.scala:25)
[error] 	at scala.meta.internal.scalacp.SymbolOps$XtensionSymbol.ssym(SymbolOps.scala:185)
[error] 	at scala.meta.internal.scalacp.TypeOps$XtensionTypeSType.loop$1(TypeOps.scala:22)
[error] 	at scala.meta.internal.scalacp.TypeOps$XtensionTypeSType.toSemanticTpe(TypeOps.scala:94)
[error] 	at scala.meta.internal.scalacp.TypeOps$XtensionTypeSType.loop$2(TypeOps.scala:108)
[error] 	at scala.meta.internal.scalacp.TypeOps$XtensionTypeSType.toSemanticSig(TypeOps.scala:139)
[error] 	at scala.meta.internal.scalacp.SymbolInformationOps$XtensionGSymbolSSymbolInformation.sig(SymbolInformationOps.scala:164)
[error] 	at scala.meta.internal.scalacp.SymbolInformationOps$XtensionGSymbolSSymbolInformation.toSymbolInformation(SymbolInformationOps.scala:251)
[error] 	at scala.meta.internal.scalacp.Scalacp.sinfos(Scalacp.scala:29)
[error] 	at scala.meta.internal.scalacp.Scalacp.$anonfun$parse$1(Scalacp.scala:17)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:366)
[error] 	at scala.meta.internal.scalacp.Scalacp.parse(Scalacp.scala:16)
[error] 	at scala.meta.internal.scalacp.Scalacp$.parse(Scalacp.scala:47)
[error] 	at scala.meta.internal.metacp.ClassfileInfos$.fromClassNode(ClassfileInfos.scala:47)
[error] 	at scala.meta.internal.symtab.GlobalSymbolTable.loadSymbol(GlobalSymbolTable.scala:38)
[error] 	at scala.meta.internal.symtab.GlobalSymbolTable.info(GlobalSymbolTable.scala:67)
[error] 	at scalafix.internal.v1.InternalSemanticDoc.info(InternalSemanticDoc.scala:75)
[error] 	at scalafix.v1.SemanticDocument.info(SemanticDocument.scala:38)
[error] 	at scalafix.v1.Symbol.info(Symbol.scala:22)
[error] 	at scalafix.internal.scaluzzi.MissingFinal.isSealed$1(MissingFinal.scala:13)
[error] 	at scalafix.internal.scaluzzi.MissingFinal.$anonfun$fix$2(MissingFinal.scala:17)
[error] 	at scalafix.internal.scaluzzi.MissingFinal.$anonfun$fix$2$adapted(MissingFinal.scala:17)
[error] 	at scala.collection.LinearSeqOptimized.exists(LinearSeqOptimized.scala:95)
[error] 	at scala.collection.LinearSeqOptimized.exists$(LinearSeqOptimized.scala:92)
[error] 	at scala.collection.immutable.List.exists(List.scala:91)
[error] 	at scalafix.internal.scaluzzi.MissingFinal.leaksSealedParent$1(MissingFinal.scala:17)
[error] 	at scalafix.internal.scaluzzi.MissingFinal.$anonfun$fix$7(MissingFinal.scala:39)
[error] 	at scalafix.internal.scaluzzi.MissingFinal.$anonfun$fix$7$adapted(MissingFinal.scala:34)
[error] 	at scalafix.internal.scaluzzi.MissingFinal$traverser$1$.apply(MissingFinal.scala:67)
[error] 	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
[error] 	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
[error] 	at scalafix.internal.scaluzzi.MissingFinal$traverser$1$.apply(MissingFinal.scala:74)
[error] 	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
[error] 	at scala.meta.transversers.Traverser.apply(Traverser.scala:4)
[error] 	at scalafix.internal.scaluzzi.MissingFinal$traverser$1$.apply(MissingFinal.scala:74)
[error] 	at scalafix.internal.scaluzzi.MissingFinal.collect(MissingFinal.scala:78)
[error] 	at scalafix.internal.scaluzzi.MissingFinal.fix(MissingFinal.scala:34)
[error] 	at scalafix.internal.v1.Rules.$anonfun$semanticPatch$1(Rules.scala:78)
[error] 	at scala.collection.immutable.List.map(List.scala:297)
[error] 	at scalafix.internal.v1.Rules.semanticPatch(Rules.scala:76)
[error] 	at scalafix.internal.v1.MainOps$.getPatchesAndDiags(MainOps.scala:305)
[error] 	at scalafix.internal.v1.MainOps$.unsafeHandleFile(MainOps.scala:255)
```

Maybe updating `scalameta` would solve this?

**Comment by enzief** [comment]
Updated scalafix version in `0.1.19`, please try it out @therockstorm

**Comment by therockstorm** [comment]
Thanks for updating! It looks like it's actually an issue with the Java version. It works with Java 8 and 11, but I still get the error running `scalafixAll` using `0.1.19` with Java 16. It works with the two `scaluzzi` rules commented out on Java 16, however.

**Comment by bjaglin** [comment]
sbt-scalafix starts a Scalafix instance built against 2.12 by default, more specifically 2.12.13 as of 0.9.28. [Official support for Java 16 was added to Scala 2.12.14](https://github.com/scala/scala/pull/9477/commits/2a60c3121ada1ec39b507aa6a6c5e36f25ea9358), so the freshly-released Scalafix 0.9.29 (built against 2.12.14) should help, without rebuilding/republishing the rule.

**Comment by bjaglin** [comment]
On another note, 0.1.19 should probably be avoided/skipped as it seems to work only with Scalafix 0.9.28, see https://gitter.im/scalacenter/scalafix?at=60b41af5688a2624b8bf52c0

**Comment by enzief** [comment]
Thanks @bjaglin

**Comment by therockstorm** [comment]
Confirmed using `scalafix` 0.9.29 and `scaluzzi` 0.1.20 works with Java 16. Thanks!
